"""add_rsvp_logs_retry

Revision ID: be501a6a779a
Revises: bd44331bcc53
Create Date: 2025-12-26 02:14:37.383551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be501a6a779a'
down_revision: Union[str, Sequence[str], None] = 'bd44331bcc53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsvp_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsvp_logs_guest_id'), 'rsvp_logs', ['guest_id'], unique=False)
    op.create_index(op.f('ix_rsvp_logs_id'), 'rsvp_logs', ['id'], unique=False)
    
    # Safe drop: only if column exists (prevents migration failure in DBs without phone_last4)
    conn = op.get_bind()
    result = conn.execute(
        sa.text("""
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'guests'
              AND column_name = 'phone_last4'
            LIMIT 1;
        """)
    ).scalar()
    
    if result:
        op.drop_column('guests', 'phone_last4')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('phone_last4', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_rsvp_logs_id'), table_name='rsvp_logs')
    op.drop_index(op.f('ix_rsvp_logs_guest_id'), table_name='rsvp_logs')
    op.drop_table('rsvp_logs')
    # ### end Alembic commands ###
